language: node_js
node_js:
- '10'
cache: yarn
script: yarn run build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
    
env:
  matrix:
    secure: PsGbtd8eJs3AbZZcm1VNj1jR1ycrqRHmzlLsn0pN4M07443UFfIVJQnKAvK2jPCKlj/2rQb6deFyHh9Lkd4pNsKMQmKBNpUu7iAVO41WY7b3o2E4LsQ+ICwLGlyOnSQwEeoDu3ht/vYJbOzYY4/xV8CBcxAiCkoeySeeJqMhiIW2RmD41M5s1FAzxG0KBvF8UnONgMmiRH3LfrRfZ3+1bf1jJz+AbP860u6rddGoZ9EWbNkx7Vc2Btcwl7SlLGPszi8HVE1OIbSicd8bYN1uqkSFO6++IkLda/0vJ5BVSKgyg1ad4pNONXUz6beu/KWadOti8SZagyg9ZV2qupVKg84V6ZEv+rckDaHudUl7WWAYfGwQK+zfvpjC7jGG4ozmMcy7agDiSls6hlGfqngboW/R1wuVt7XCpQNRUtA+uvXuO1z9DiYwM97/6r27b9fOkpHkjzjkNsVB6GvylOtrtuEcyd0mcvwyKlaVHKeVoBLcwNhdEHT+cjpeDeeqrdpIE1bu/f+1cnDEp+Lpr1ZmWzrKBvFEBvX6oN8k5rLN3QnNlD+UlxpzufI7UThfB6Q+Zm7texxl71f2yzUOd7CRoAUGv5IV14785bdA71ztKBwqoFBmofuVcs8nDrZqgH4sAICg4bgKddqELpWDPVOK19KRvaoCJuctaAg20xK5w6o=
